### ISSUE TITLE
Why do not use six.PY2 in python version verification?

### ISSUE THREAD

**Issue by fabiothz** [orsinium/homoglyphs#3]
In line 9 of the file core.py, there is a condition for the verification of the python version. However, in django framework this do not work.

Don't we can change this to "six.PY2" verification?

**Comment by orsinium** [comment]
This verification only for two functions. I don't need side package for it. Six is useful package for big projects. For example, I use it in DjBurger.

**Comment by fabiothz** [comment]
Also we can use:

```
import sys

if sys.version_info[0] == 2:
    range = xrange  # noQA
    chr = unichr  # noQA
```

**Comment by orsinium** [comment]
Yeah, good idea :) Do you want make pull request? Or I'm made commit myself?

**Comment by fabiothz** [comment]
I made it!
This is in commit b2886e10d4522dc6efe9332eb9a801d4b8f5c8c1

**Comment by orsinium** [comment]
Good. Thank you for contributing :)
