### ISSUE TITLE
source of confusables.json

### ISSUE THREAD

**Issue by ariutta** [orsinium/homoglyphs#7]
I came across another item I'm trying to figure out. The **homoglyphs** package appears to return just the originals as homoglyphs for `w` and for `ㅋ`:
```py
import json
import homoglyphs as hg
homoglyphs = None
with open(hg.Languages().fpath) as f:
  languages = set(json.load(f))
  homoglyphs = hg.Homoglyphs(languages=languages)
  print(homoglyphs.get_combinations('w'))
  # >> ['w']
  print(homoglyphs.get_combinations('ㅋ'))
  # >> ['ㅋ']
```

But the Unicode site gives the original plus [22 additional homoglyphs](https://unicode.org/cldr/utility/confusables.jsp?a=w&r=None) for `w`:
> 𝐰 𝗐 ᴡ ѡ ա ꮃ 𝔴 𝕨 𝓌 𝙬 ɯ 𝔀 𝚠 𑜏 𑜎 𝑤 𝘄 w 𝒘 𝘸 𝖜 ԝ 𑜊

and the original plus [2 additional homoglyphs](https://unicode.org/cldr/utility/confusables.jsp?a=%E3%85%8B&r=None) for `ㅋ`:
> ㅋ ᄏ ᆿ

The **confusable_homoglyphs** package appears to give the same results as the Unicode site for `w`. For `ᄏ`, **confusable_homoglyphs** yields just one additional homoglyph initially, but it yields another when you look for homoglyphs of that first result:
```py
from confusable_homoglyphs import confusables
ws = confusables.is_confusable('w', preferred_aliases=[], greedy=True)
set(map(lambda x: x['c'], ws[0]['homoglyphs']))
# >> {'ꮃ', 'ա', 'ᴡ', '𝒘', '𝐰', '𝗐', '𝘸', '𝚠', '𝕨', '𑜊', '𝙬', '𝖜', '𑜎', 'ɯ', '𝔴', '𑜏', '𝑤', 'ѡ', '𝔀', '𝘄', '𝓌', 'ԝ'}
khieukh1s = confusables.is_confusable('ㅋ', preferred_aliases=[], greedy=True)
set(map(lambda x: x['c'], khieukh1s[0]['homoglyphs']))
# >> {'ᄏ'}
khieukh2s = confusables.is_confusable('ᄏ', preferred_aliases=[], greedy=True)
set(map(lambda x: x['c'], khieukh2s[0]['homoglyphs']))
# >> {'ㅋ', 'ᆿ'}
```

When I compare the file sizes of `confusables.json`, the one for **confusable_homoglyphs** is `901246B` whereas the one for **homoglyphs** is `869317B`, so they seem to be different files.

Does the homoglyphs package pull the [latest confusables.txt](http://www.unicode.org/Public/security/latest/confusables.txt) from the Unicode site?

**Comment by orsinium** [comment]
Thank you for your report! Sorry for veeeeery late answer. I have some troubles in my life related to difficult relocation.

I've updated data files in the project. Also I've added `get_all` method to Languages and Categories:

```python
# get all languages
hg.Languages.get_all()
# {'nl', 'lt', ..., 'de', 'mk'}

# get all categories
hg.Categories.get_all()
# {'RUNIC', 'DESERET', ..., 'SOGDIAN', 'TAI_LE'}
```

Here is actual code for checking homoglyphs from your issue:

```python
import homoglyphs as hg
homoglyphs = hg.Homoglyphs(categories=hg.Categories.get_all())
len(homoglyphs.get_combinations('w'))
len(homoglyphs.get_combinations('ㅋ'))
```

Differences between your results and actual data also related to your alphabet initialization: `Languages` doesn't contain all glyphs, opposite to `Categories`. Please, use `Categories` anywhere you can.

Thank you for project usage. I hope, you found it useful for your tasks :)

**Comment by ariutta** [comment]
Thank you! And I hope your life is going better now.
