### ISSUE TITLE
Suggested homoglyphs

### ISSUE THREAD

**Issue by cathalgarvey** [orsinium/homoglyphs#8]
Hi @orsinium - thank you so much for this library, I'm investigating it for use in an anti-spambot project right now. The spambots use a lot of homoglyph-mangling to avoid filtering. Probably the dumb but effective solution is simply to ban messages containing mixed glyph families, for now. :)

In any case, while experimenting I discovered a few homoglyphs that are apparently not covered right now:

`TAI_LE`: `ᥱᥒ`
`COMMON`: `／`
`LATIN`: `ⅿ`

..is there a contribution guide for these that I could follow, and I'll go add them? Or, perhaps they are already covered and I'm outdated/doing-it-wrong. :)

**Comment by orsinium** [comment]
Hi. Thank you for usage. I hope, you've founded it useful :)

3 from 4 of this glyphs already in lib:

```python
alphabet = hg.Categories.get_alphabet(('TAI_LE', ))
'ᥱ' in alphabet  # True
'ᥒ' in alphabet  # True

alphabet = hg.Categories.get_alphabet(('LATIN', ))
'ⅿ' in alphabet  # True

alphabet = hg.Categories.get_alphabet(('COMMON', ))
'／' in alphabet  # False
```

Source information about glyphs loaded via [confusable_homoglyphs parser](https://github.com/vhf/confusable_homoglyphs/blob/master/confusable_homoglyphs/cli.py) from [unicode.org](http://www.unicode.org/Public/UNIDATA/Scripts.txt). I see "FULLWIDTH SOLIDUS" in this database. I'll check it in downloaded data later. Thank you for issue :)

**Comment by orsinium** [comment]
Yeah, I've found it. Please, update lib:
```
pip3 install --no-cache-dir -U homoglyphs
```

**Comment by cathalgarvey** [comment]
Thanks! ;)
