### ISSUE TITLE
Fails for U+3161 : HANGUL LETTER EU

### ISSUE THREAD

**Issue by ariutta** [orsinium/homoglyphs#9]
I got an error for character `U+3161` (HANGUL LETTER EU). Here's code to reproduce the error:

```py
import homoglyphs as hg

hg_instance = hg.Homoglyphs(categories=hg.Categories.get_all(),
                           strategy=hg.STRATEGY_LOAD,
                           ascii_strategy=hg.STRATEGY_REMOVE)

hg_instance.to_ascii('ㅡ')
```

### Expected

[Unicode site results](https://unicode.org/cldr/utility/confusables.jsp?a=%E3%85%A1&r=None)

### Actual

>  File "homoglyphs/core.py", line 237, in to_ascii
    return self.uniq_and_sort(self._to_ascii(text))
  File "homoglyphs/core.py", line 170, in uniq_and_sort
    result = list(set(data))
  File "/homoglyphs/core.py", line 233, in _to_ascii
    if max(map(ord, variant)) < 256:
ValueError: max() arg is an empty sequence

**Comment by ariutta** [comment]
Other characters that make it fail:

```
疊
뾰
ᅳ而營
新
CONTROLVECTORSLINC00312VECTORSSI-CONTROLSI-LINC00312
TIME(S)507090110130150170190M
으
IM(UM)00.010.11.00.10.10.11.0
ΔΔ
ΔΔ
ΔΔ
homoglyphs could not handle this character:
ΔΔ
亏
느
느
ㄣ
니
เชาอว
야
001411:0070310.0510102108T01609:0220.11006
```

**Comment by orsinium** [comment]
Good news: I've fixed this exception and made some optimizations. Please, update the library to v.1.3.2:

```bash
pip3 install --no-cache-dir -U homoglyphs
```

Bad news: [official list of homoglyphs](ftp://ftp.unicode.org/Public/security/latest/confusables.txt) provides strange information about dash-similar glyphs.

```python
h = Homoglyphs(categories=Categories.get_all())
h.get_combinations('\u3161')
['ᅳ', '—', '―', '─', '━', '⼀', 'ー', 'ㅡ', '㇐', '一', 'ꟷ', '－']
```
There is all 12 symbols that presented [in your link](https://unicode.org/cldr/utility/confusables.jsp?a=%E3%85%A1&r=None). However, there is no `-` symbol, so `to_ascii` can't convert it. I don't know why Unicode Consorcium didn't include it in list. You can ask them. Please, let me know if them provide some information for you or add new glyphs into table.
